# Generated by Django 6.0 on 2025-12-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Автордың аты-жөні')),
                ('gender', models.CharField(blank=True, choices=[('Er', 'Ер'), ('Ayel', 'Әйел')], max_length=20, null=True, verbose_name='Жынысы')),
                ('bio', models.TextField(blank=True, verbose_name='Өмірдерегі')),
                ('main_works', models.TextField(blank=True, verbose_name='Негізгі еңбектері')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторлар',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория аты')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Шығарма аты')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанры')),
                ('genre_type', models.CharField(blank=True, max_length=100, verbose_name='Жанрлық түрі')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='Стилі')),
                ('chronotope', models.CharField(blank=True, max_length=200, verbose_name='Хронотопы')),
                ('theme', models.TextField(blank=True, verbose_name='Тақырыбы')),
                ('abstract', models.TextField(blank=True, verbose_name='Қысқаша аңдатпа')),
                ('created_year', models.CharField(blank=True, max_length=50, verbose_name='Жазылған жылы/уақыты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шығарма',
                'verbose_name_plural': 'Шығармалар',
            },
        ),
        migrations.CreateModel(
            name='CorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=255, verbose_name='Сөз/Тіркес/Кейіпкер аты')),
                ('meaning', models.TextField(blank=True, verbose_name='Мағынасы/Талдауы')),
                ('example_text', models.TextField(blank=True, verbose_name='Мәтіндегі қолданысы (Мысал)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Санаты')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.work', verbose_name='Шығарма')),
            ],
            options={
                'verbose_name': 'Корпус жазбасы',
                'verbose_name_plural': 'Корпус жазбалары',
            },
        ),
    ]
