# Generated by Django 6.0 on 2025-12-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/', verbose_name='Сурет')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Дұрыс жауап (Сөз немесе Шығарма аты)')),
            ],
            options={
                'verbose_name': 'Ойын суреті',
                'verbose_name_plural': 'Ойын суреттері',
            },
        ),
        migrations.AlterField(
            model_name='work',
            name='created_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Жазылған жылы'),
        ),
    ]
